# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-20 22:42
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blackBelt_app', '0004_trip'),
    ]

    operations = [
        migrations.AddField(
            model_name='trip',
            name='created_by',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='Trips', to='blackBelt_app.User'),
            preserve_default=False,
        ),
    ]
